const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const profileSchema = new Schema({
  _id: { type: String },
  last_name: { type: String, required: true },
  first_name: { type: String, required: true },
  middle_name: { type: String, required: true },
  d_o_b: { type: String, required: false },
  place_of_birth: { type: String, required: false },
  ss_number: { type: String, required: false },
  email_address: { type: String, required: false },
  phone_number: { type: String, required: false },
  address_one: { type: String, required: false },
  address_two: { type: String, required: false },
  city: { type: String, required: false },
  state: { type: String, required: false },
  zipcode: { type: String, required: false },
  country: { type: String, required: false },
  other_names_used: { type: String, required: false },
  more_names_used: { type: String, required: false },
  parent_one_first_and_middle_name: { type: String, required: false },
  parent_one_last_name: { type: String, required: false },
  parent_one_dob: { type: String, required: false },
  parent_place_of_birth: { type: String, required: false },
  parent_two_first_and_middle_name: { type: String, required: false },
  parent_two_last_name: { type: String, required: false },
  parent_two_dob: { type: String, required: false },
  parent_two_place_of_birth: { type: String, required: false },
  full_name_of_spouse: { type: String, required: false },
  spouse_d_o_b: { type: String, required: false },
  current_spouse_place_of_birth: { type: String, required: false },
  date_of_marriage: { type: String, required: false },
  widow_divorce_date: { type: String, required: false },
  additional_phone_number: { type: String, required: false },
  occupation: { type: String, required: false },
  employer_or_school: { type: String, required: false },
  height: { type: String, required: false },
  hair_color: { type: String, required: false },
  eye_color: { type: String, required: false },
  departure_date: { type: String, required: false },
  return_date: { type: String, required: false },
  coutries_to_be_visited: { type: String, required: false },
  perm_address: { type: String, required: false },
  perm_apartment: { type: String, required: false },
  perm_city: { type: String, required: false },
  perm_state: { type: String, required: false },
  perm_zip: { type: String, required: false },
  em_contact_name: { type: String, required: false },
  em_contact_address: { type: String, required: false },
  em_contact_apartment: { type: String, required: false },
  em_contact_city: { type: String, required: false },
  em_contact_state: { type: String, required: false },
  em_contact_zip_code: { type: String, required: false },
  em_contact_phone: { type: String, required: false },
  em_contact_relationship: { type: String, required: false },
  recent_passport_printed_name: { type: String, required: false },
  recent_passport_book_number: { type: String, required: false },
  recent_passport_issue_date: { type: String, required: false },
  recent_passport_card_printed_name: { type: String, required: false },
  recent_passport_card_number: { type: String, required: false },
  recent_passport_card_issue_date: { type: String, required: false },
});

const Profile = mongoose.model("Profile", profileSchema);

module.exports = Profile;
